// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MLGS;
using System;

namespace MLGS.Migrations
{
    [DbContext(typeof(ParcelContext))]
    [Migration("20180310212056_FloatUpdate")]
    partial class FloatUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MLGS.ParcelData", b =>
                {
                    b.Property<int>("ParcelDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Humidity");

                    b.Property<float>("Light");

                    b.Property<float>("Pression");

                    b.Property<float>("Temperature");

                    b.HasKey("ParcelDataId");

                    b.ToTable("ParselsData");
                });
#pragma warning restore 612, 618
        }
    }
}
